### ISSUE TITLE
RO_00002560 and RO_0002561 need to be updated in RO

### ISSUE THREAD

**Issue by robgur** [tucotuco/bco#40] opened 2015-03-09 22:57 UTC
These two terms are being imported from ro_eco subset without annotations.  They aren't currently being used in BCO.

**Comment by rlwalls2008** [comment] 2015-03-10 16:07
Actually, the issue is that the full eco-subset is not built yet. Once it is ready, these relations will be imported automatically.

**Comment by rlwalls2008** [comment] 2015-03-20 00:11
These are annotation properties that are included in the eco subset. We don't need them for now, so I am closing this issue.

**Closed** 2015-03-20 00:12 UTC
Labels: external dependency

**Comment by rlwalls2008** [comment] 2015-03-20 00:15
I think this was supposed to be RO_0002352 and RO_0002353. In any case, the issue is solved by importing RO core.
